# Generated by Django 5.1.15 on 2026-01-10 12:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TareasDWES', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateField()),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('grupal', 'Grupal')], max_length=10)),
                ('requiere_validacion', models.BooleanField(default=False)),
                ('validada', models.BooleanField(default=False)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL)),
                ('profesor_validador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_a_validar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TareaGrupal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaboradores', models.ManyToManyField(related_name='tareas_grupales', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_grupal', to='TareasDWES.tarea')),
            ],
        ),
    ]
