# Generated by Django 5.1.15 on 2026-01-11 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TareasDWES', '0002_tarea_tareagrupal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='profesor_validador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_a_validar', to=settings.AUTH_USER_MODEL),
        ),
    ]
